services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    extends:
      file: ../common.yml
      service: base
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.lab.nobasura.org # autodiscovery domain response
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${APP_DATA}/jellyfin:/config
      - ${DATA_DIR}/media:/data/media
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
