networks:
  default:
    name: obs-shared
    external: true
  socket_proxy:

include:
  - socket-proxy.yml
  - beszel.yml
  - dozzle.yml
  - gotify.yml
  - slack2gotify.yml
  - portainer.yml
  - uptime-kuma.yml
