services:
  gotify:
    extends:
      file: ../common.yml
      service: base
    image: gotify/server:2.8.0
    container_name: gotify
    volumes:
      - gotify-data:/app/data
    ports:
      - 80:80

volumes:
  gotify-data:
    name: gotify-data
