volumes:
  portainer-data:
    name: portainer-data

services:
  portainer:
    image: portainer/portainer-ee:2.33.6
    container_name: portainer
    extends:
      file: ../common.yml
      service: socket-base
    ports:
      - 9900:9000
    volumes:
      - portainer-data:/data
    labels:
      - deunhealth.restart.on.unhealthy=true
