---
# https://gethomepage.dev/configs/bookmarks

- Ops:
    - Grafana:
        - abbr: GR
          href: https://grafana.lab.nobasura.org/
    - Dozzle:
        - abbr: DZ
          href: https://dozzle.lab.nobasura.org/
    - Uptime Kuma:
        - abbr: UK
          href: https://uptime-kuma.lab.nobasura.org/

- Dev:
    - homelab repo:
        - abbr: GH
          href: https://github.com/punk-dev-robot/homelab
    - Linear:
        - abbr: LI
          href: https://linear.app/
