services:
  deunhealth:
    image: qmcgaw/deunhealth@sha256:fca3832ace35e3c028d3ec2e6271ac1161ed302b75b34e9dd01db1c106a25802
    container_name: deunhealth
    extends:
      file: ../common.yml
      service: socket-base
    environment:
      HEALTH_SERVER_ADDRESS: 127.0.0.1:9999
