services:
  bazarr:
    image: linuxserver/bazarr:v1.5.3-ls325
    container_name: bazarr
    extends:
      file: ../common.yml
      service: base
    ports:
      - "6767:6767"
    volumes:
      - ${DATA_DIR}:/data
      - ${APP_DATA}/bazarr:/config
