services:
  flaresolverr:
    extends:
      file: ../common.yml
      service: base
    image: flaresolverr/flaresolverr:v3.4.6
    container_name: flaresolverr
    environment:
      LOG_HTML: false
      # CAPTCHA_SOLVER: none
    ports:
      - 8191:8191
