services:
  gluetun:
    extends:
      file: ../common.yml
      service: base
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    labels:
      - "deunhealth.restart.on.unhealthy=true"
    ports:
      # - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
      - 8112:8112/tcp # Deluge Web Client
      - 58846:58846/tcp # Deluge daemon
      # - 8081:8080/tcp # qBittorrent
    volumes:
      - ${APP_DATA}/gluetun:/gluetun
    environment:
      # Wireguard
      VPN_SERVICE_PROVIDER: surfshark
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $WIREGUARD_PRIVATE_KEY
      # TODO: move to env
      WIREGUARD_ADDRESSES: 10.14.0.2/16
      SERVER_COUNTRIES: Netherlands,Belgium
      # TODO: do I want this as local dns?
      DNS_ADDRESS: 10.10.10.53
      DOT: off
      HTTPPROXY: off
      SHADOWSOCKS: off
      # FIREWALL_DEBUG: true
      FIREWALL_OUTBOUND_SUBNETS: 172.29.12.0/22,172.29.8.0/22,10.10.10.0/24
