services:
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    extends:
      file: ../common.yml
      service: base
    image: golift/notifiarr@sha256:4180afa7df046312ac1dd08574a9fd23eae0d2828c126f0113314a6b5643cc82
    ports:
      - "5454:5454"
    volumes:
      - ${APP_DATA}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    environment:
      - DN_AUTO_UPDATE=off
