services:
  nzbget:
    extends:
      file: ../common.yml
      service: base
    image: linuxserver/nzbget:v25.4-ls222
    container_name: nzbget
    ports:
      - 6789:6789
    volumes:
      - ${DATA_DIR}/usenet:/data/usenet
      - $APP_DATA/nzbget:/config
