services:
  recyclarr:
    extends:
      file: ../common.yml
      service: base
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: $PUID:$PGID
    volumes:
      - ${APP_DATA}/recyclarr:/config
    environment:
      RECYCLARR_CREATE_CONFIG: false
