services:
  enclosed:
    extends:
      file: ../common.yml
      service: base
    image: corentinth/enclosed:1.16.0
    container_name: enclosed
    ports:
      - "8787:8787"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8787/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s