services:
  deunhealth:
    image: qmcgaw/deunhealth@sha256:db1e4fcd3aceeb0da34a83f7a8a5432df586e6d0388ddb6ad8dd7b479e4aa25d
    container_name: deunhealth
    extends:
      file: ../common.yml
      service: socket-base
    environment:
      HEALTH_SERVER_ADDRESS: 127.0.0.1:9999
