services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    extends:
      file: ../common.yml
      service: socket-base
    command: agent
    ports:
      - 7007:7007
    environment:
      DOZZLE_LEVEL: info
