services:
  beszel-agent:
    image: henrygd/beszel-agent:0.15.4-alpine
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOB3xpJfk3I98kubMgbfR5hlV3Y4YAy1yTcV/BQJVaW9"
      TOKEN: ${BESZEL_AGENT_VPS}
      HUB_URL: https://beszel.nobasura.org
