- name: Docker setup
  include_tasks: setup.yml
  when: docker_setup

- name: Docker host firewall (DOCKER-USER)
  include_tasks: firewall.yml
  when: docker_user_restricted_ports is defined

- name: Deploying stack
  include_tasks: deploy_stack.yml
  when: docker_deploy
  loop: "{{ stacks }}"
  loop_control:
    loop_var: cur_stack

- name: Deploying newt tunnel stack
  include_tasks: deploy_stack.yml
  when: docker_deploy and deploy_tunnels | default(false) and pangolin_newt_enabled | default(false)
  vars:
    cur_stack: newt
